export const TAROT_CARDS = [
    "愚者 (The Fool)",
    "魔術師 (The Magician)",
    "女教皇 (The High Priestess)",
    "女帝 (The Empress)",
    "皇帝 (The Emperor)",
    "法王 (The Hierophant)",
    "恋人 (The Lovers)",
    "戦車 (The Chariot)",
    "力 (Strength)",
    "隠者 (The Hermit)",
    "運命の輪 (Wheel of Fortune)",
    "正義 (Justice)",
    "吊るされた男 (The Hanged Man)",
    "死神 (Death)",
    "節制 (Temperance)",
    "悪魔 (The Devil)",
    "塔 (The Tower)",
    "星 (The Star)",
    "月 (The Moon)",
    "太陽 (The Sun)",
    "審判 (Judgement)",
    "世界 (The World)"
];
